# Generated by Django 4.0.5 on 2022-07-02 15:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('station_id', models.CharField(max_length=255, verbose_name='Station ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Station coordinates')),
                ('configuration', models.JSONField(blank=True, null=True, verbose_name='Station configuration')),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'ChargingStations',
            },
        ),
    ]
